# Start with the docker-compose version to be used
version: "3"
# A service is "kind of a container"
services:
  # Give a name for the first service
  redis-server:
    image: "redis"
  # Give a name for the second service
  node-app:
    restart: on-failure
    # Look in the current directory for a DOCKERFILE and use it to build
    build: .
    # Specify the ports for the container
    ports:
      # The dash in a yammel file is an array
      # Map port on local machine to a port insie of the container
      - "4001:8081"
